### ISSUE TITLE
hu.pdf is constructed from hu.tex

### ISSUE THREAD

**Issue by phs75** [Galfour/ialr#2]
Merci de ne pas mettre hu.pdf sur le repo, c'est un fichier généré à partir de hu.tex, chacun a un compilateur latex différent, et les diffs entre deux commits ne veulent rien dire.

**Comment by Galfour** [comment]
Le but est de pouvoir le consulter rapidement depuis un smartphone ou une
machine sans latex ou copie locale du repository

**Comment by phs75** [comment]
OK, je n'avais pas pensé à cette situation. Quelle est la bonne façon de gérer ça ? Peut-on configurer le repo pour ne jamais avoir des conflits sur hu.pdf quand on fait on merge ?

**Comment by Galfour** [comment]
S'il y a un conflit, un nouveau commit doit être fait : le pdf n'intègre
pas les modifications des deux derniers commits
